### ISSUE TITLE
[Feature Request] Include basic parsing in the component directly

### ISSUE THREAD

**Issue by arsaboo** [ljmerza/ha-email-sensor#1]
It will be great if we can include some basic parsing in the component directly. The config could be something like:
```yaml
sensor:
  - platform: email
    email: !secret my_email
    password: !secret my_google_app_password
    monitored_conditions:
      - usps   
```
