### ISSUE TITLE
UPS doesn't parse 'My Choice' emails

### ISSUE THREAD

**Issue by McSwindler** [ljmerza/ha-email-sensor#15]
## Version of the custom_component
2.0.1

## Configuration

```yaml
sensor:
  - platform: email
    email: !secret gmail_email
    password: !secret gmail_password
```

## Describe the bug
When signed up for the 'My Choice' service from UPS, the tracking emails come from the address `mcinfo@ups.com` 
It doesn't look like this address is setup to be parsed.
