### ISSUE TITLE
everything works but the tracking numbers do not go up

### ISSUE THREAD

**Issue by phenixtai** [ljmerza/ha-email-sensor#35]
## Version of the custom_component
2.15.0

## Configuration

sensor:
 - platform: email
   email: xxxxxxx@gmail.com
   password: ksrnhtgcpljxoayl

Add your logs here.
Everything is ok, but as a result on the attribute of the sensor I have:
```

## Describe the bug



emails: 
- from:
    - - AliExpress
      - transaction@notice.aliexpress.com
  subject: Confirmation d’expédition de votre commande 301xxxxxxxxxxxxx6
- from:
    - - AliExpress
      - transaction@notice.aliexpress.com
  subject: Confirmation d’expédition de votre commande 301xxxxxxxxxxxx

tracking_numbers: 
ups: []
fedex: []
paypal: []
usps: []
ali_express: []
newegg: []
rockauto: []
bh_photo: []
ebay: []
dhl: []
hue: []
google_express: []
western_digital: []
monoprice: []
georgia_power: []
best_buy: []
dollar_shave_club: []
nuleaf: []
timeless: []
BESPOKE_POST: []
wyze: []
reolink: []
chewy: []
groupon: []
zazzle: []
home_depot: []
swiss_post: []
manta_sleep: []

count: 2
icon: mdi:email
friendly_name: email_xxxxxx@gmail.com

```
---> suddenly no tracking number is filled on the appropriate map card on lovelace : 

type: custom:tracking-number-card
entities:
  - sensor.email_xxxxxx_gmail_com
hideWhenEmpty: false

I do not understand why the parser does not find the tracking number, could you help me?
