### ISSUE TITLE
Is a sensor only created when an applicable email is found?

### ISSUE THREAD

**Issue by rpitera** [ljmerza/ha-email-sensor#9]
Just installed this and trying to see if it is working.  I don't get any errors but I also don't see a sensor created.  

Does the sensor get created only when a qualifying email is found and parsed or should I see a sensor once the component initializes whether or not a qualifying email is found?

**Comment by ljmerza** [comment]
You should see a sensor. Maybe you're getting an error try enable logging for it

**Comment by rpitera** [comment]
Can I enable debug for this sensor only by adding this to my logger options 

```
logger:
  default: error
  logs:    
    homeassistant.components.email: debug
```


or do I have the name wrong?
